# Generated by Django 6.0.4 on 2026-04-13 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề hội thoại')),
                ('last_question', models.TextField(blank=True, null=True, verbose_name='Câu hỏi cuối cùng')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Tổng số tin nhắn')),
                ('total_documents', models.IntegerField(default=0, verbose_name='Tổng số tài liệu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Đoạn hội thoại',
                'verbose_name_plural': 'Đoạn hội thoại',
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên người dùng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Tên file')),
                ('file_path', models.CharField(max_length=500, verbose_name='Đường dẫn file')),
                ('file_size', models.IntegerField(verbose_name='Kích thước (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày upload')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.conversation', verbose_name='Hội thoại')),
            ],
            options={
                'verbose_name': 'Tài liệu',
                'verbose_name_plural': 'Tài liệu',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Người dùng'), ('assistant', 'Trợ lý')], max_length=20, verbose_name='Vai trò')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation', verbose_name='Hội thoại')),
            ],
            options={
                'verbose_name': 'Tin nhắn',
                'verbose_name_plural': 'Tin nhắn',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='QuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Câu hỏi')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian hỏi')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.conversation', verbose_name='Hội thoại')),
            ],
            options={
                'verbose_name': 'Lịch sử câu hỏi',
                'verbose_name_plural': 'Lịch sử câu hỏi',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.user', verbose_name='Người dùng'),
        ),
    ]
